apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-config
  labels:
    spring.cloud.kubernetes.config: "true"
data:
  application.yml: |-
    bean:
      message: Hello World!
    another:
      property: value
    management:
      security:
        enabled: false
      endpoints:
        enabled-by-default: true
        web:
          exposure:
            include: "*"